//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final_Project.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Database1Entities3 : DbContext
    {
        public Database1Entities3()
            : base("name=Database1Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Art> Arts { get; set; }
        public DbSet<English> Englishes { get; set; }
        public DbSet<GK> GKs { get; set; }
        public DbSet<Image> Images { get; set; }
        public DbSet<Mathematic> Mathematics { get; set; }
        public DbSet<Movy> Movies { get; set; }
        public DbSet<Reg_User> Reg_User { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
